spring:
  application:
    name: risk-service

server:
  port: 8084

marketdata:
  url: ${MARKETDATA_URL:http://localhost:8081}

portfolio:
  url: ${PORTFOLIO_URL:http://localhost:8082}

risk:
  engine:
    url: ${RISK_ENGINE_URL:http://localhost:8090}

logging:
  level:
    root: INFO
