spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/portfolio}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  application:
    name: portfolio-service

server:
  port: 8082

marketdata:
  url: ${MARKETDATA_URL:http://localhost:8081}

logging:
  level:
    root: INFO
